server:
  port: 80
 
spring: 
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://43.245.223.83:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: hgr
    password: Hgr123456.
  jpa: 
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  
ttp: 
  encoding: 
    charset: UTF-8
    enabled: true
  