server:
  port: 80
 
spring: 
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://43.245.223.83:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: hgr
    password: Hgr123456.
    type: com.alibaba.druid.pool.DruidDataSource
ttp: 
  encoding: 
    charset: UTF-8
    enabled: true
  